import { blockPathGetter } from '@/front-end/motion-blocks/core/keyframes';
import type { KeyframePropertyDef } from '@/front-end/motion-blocks/core/keyframes';

export const PRIMITIVE3D_KEYFRAME_PROPERTIES: KeyframePropertyDef[] = [
    {
        path: 'params.object.positionX',
        label: 'Object X',
        shortLabel: 'X',
        kind: 'moving',
        defaultInterpolation: 'linear',
        getValue: blockPathGetter('params.object.positionX'),
        min: -20,
        max: 20,
        step: 0.01,
    },
    {
        path: 'params.object.positionY',
        label: 'Object Y',
        shortLabel: 'Y',
        kind: 'moving',
        defaultInterpolation: 'linear',
        getValue: blockPathGetter('params.object.positionY'),
        min: -20,
        max: 20,
        step: 0.01,
    },
    {
        path: 'params.object.positionZ',
        label: 'Object Z',
        shortLabel: 'Z',
        kind: 'moving',
        defaultInterpolation: 'linear',
        getValue: blockPathGetter('params.object.positionZ'),
        min: -20,
        max: 20,
        step: 0.01,
    },
    {
        path: 'params.object.rotationX',
        label: 'Rotate X',
        shortLabel: 'Rot X',
        kind: 'moving',
        defaultInterpolation: 'linear',
        getValue: blockPathGetter('params.object.rotationX'),
        min: -360,
        max: 360,
        step: 1,
    },
    {
        path: 'params.object.rotationY',
        label: 'Rotate Y',
        shortLabel: 'Rot Y',
        kind: 'moving',
        defaultInterpolation: 'linear',
        getValue: blockPathGetter('params.object.rotationY'),
        min: -360,
        max: 360,
        step: 1,
    },
    {
        path: 'params.object.rotationZ',
        label: 'Rotate Z',
        shortLabel: 'Rot Z',
        kind: 'moving',
        defaultInterpolation: 'linear',
        getValue: blockPathGetter('params.object.rotationZ'),
        min: -360,
        max: 360,
        step: 1,
    },
    {
        path: 'params.object.scale',
        label: 'Object Scale',
        shortLabel: 'Scale',
        kind: 'moving',
        defaultInterpolation: 'linear',
        getValue: blockPathGetter('params.object.scale'),
        min: 0.05,
        max: 10,
        step: 0.01,
    },
    {
        path: 'params.material.roughness',
        label: 'Roughness',
        shortLabel: 'Rough',
        kind: 'moving',
        defaultInterpolation: 'linear',
        getValue: blockPathGetter('params.material.roughness'),
        min: 0,
        max: 1,
        step: 0.01,
    },
    {
        path: 'params.material.metalness',
        label: 'Metalness',
        shortLabel: 'Metal',
        kind: 'moving',
        defaultInterpolation: 'linear',
        getValue: blockPathGetter('params.material.metalness'),
        min: 0,
        max: 1,
        step: 0.01,
    },
    {
        path: 'params.material.opacity',
        label: 'Material Opacity',
        shortLabel: 'Mat Opac',
        kind: 'moving',
        defaultInterpolation: 'linear',
        getValue: blockPathGetter('params.material.opacity'),
        min: 0,
        max: 1,
        step: 0.01,
    },
    {
        path: 'params.lighting.directionalIntensity',
        label: 'Local Light Intensity',
        shortLabel: 'Light',
        kind: 'moving',
        defaultInterpolation: 'linear',
        getValue: blockPathGetter('params.lighting.directionalIntensity'),
        min: 0,
        max: 20,
        step: 0.01,
    },
];
